using System.Collections.Generic;
using System.Linq;



namespace ElonaCreator
{
    static class ItemIdTable
    {
        public static bool IsValid(int id)
        {
            return 0 <= id && id < table.Length;
        }


        public static string ToString(int id)
        {
            return table[id];
        }


        public static List<string> GetAll()
        {
            return table.ToList();
        }


        private static string[] table =
        {
            "gold bar",
            "long sword",
            "dagger",
            "hand axe",
            "club",
            "magic hat",
            "fairy hat",
            "breastplate",
            "robe",
            "decorated gloves",
            "thick gauntlets",
            "heavy boots",
            "composite boots",
            "decorative ring",
            "scroll of identify",
            "scroll of oracle",
            "scroll of teleportation",
            "scroll of incognito",
            "rod of identify",
            "rod of teleportation",
            "spellbook of teleportation",
            "spellbook of identify",
            "spellbook of uncurse",
            "book",
            "book",
            "bugged book",
            "bottle of dirty water",
            "potion of blindness",
            "potion of confusion",
            "potion of paralysis",
            "sleeping drug",
            "bottle of crim ale",
            "spellbook of ice bolt",
            "spellbook of fire bolt",
            "spellbook of lightning bolt",
            "earth crystal",
            "mana crystal",
            "sun crystal",
            "gold bar",
            "raw ore of rubynus",
            "raw ore of mika",
            "raw ore of emerald",
            "raw ore of diamond",
            "wood piece",
            "junk stone",
            "garbage",
            "broken vase",
            "washing",
            "bonfire",
            "flag",
            "broken sword",
            "bone fragment",
            "skeleton",
            "tombstone",
            "gold piece",
            "platinum coin",
            "<Diablo>",
            "<Zantetsu>",
            "long bow",
            "knight shield",
            "pistol",
            "arrow",
            "bullet",
            "<Scythe of Void>",
            "<Mournblade>",
            "light cloak",
            "girdle",
            "decorative amulet",
            "potion of cure minor wound",
            "potion of cure major wound",
            "potion of cure critical wound",
            "potion of healing",
            "potion of healer",
            "<Ragnarok>",
            "potion of healer <Odina>",
            "potion of healer <Eris>",
            "potion of healer <Jure>",
            "round chair",
            "bookshelf",
            "luxury drawer",
            "boring bed",
            "rag doll",
            "toy",
            "modern table",
            "dining table",
            "armor",
            "lot of goods",
            "lot of accessories",
            "grand piano",
            "bar table alpha",
            "bar table beta",
            "barrel",
            "modern chair",
            "pick",
            "lantern",
            "decorative armor",
            "anvil",
            "closed pot",
            "open pot",
            "academic table",
            "rack of potions",
            "square chair",
            "cheap chair",
            "cupboard",
            "barn",
            "neat shelf",
            "closet",
            "variety of tools",
            "variety of goods",
            "well",
            "variety of clothes",
            "furnace",
            "oven",
            "sign",
            "crossroad sign",
            "board",
            "spellbook of minor teleportation",
            "empty basket",
            "spellbook of summon monsters",
            "rod of cure minor wound",
            "rod of magic missile",
            "rod of summon monsters",
            "rod of ice bolt",
            "rod of fire bolt",
            "show case of breads",
            "rod of heal",
            "beaker",
            "alchemy kit",
            "pentagram",
            "small foliage plant",
            "rose",
            "large foliage plant",
            "sage",
            "gazania",
            "nerine",
            "anemos",
            "foxtail grass",
            "carnation",
            "statue ornamented with plants",
            "statue ornamented with flowers",
            "canvas",
            "map",
            "food maker",
            "bundle of bows",
            "bundle of weapons",
            "decorated cloth",
            "decorated armor",
            "statue of armor",
            "disorderly book",
            "lot of books",
            "craft rack",
            "craft book shelf",
            "lot of alcohols",
            "kitchen",
            "sink",
            "kitchen oven",
            "narrow dining table",
            "elegant table",
            "gorgeous candlestick",
            "simple shelf",
            "sewing kit",
            "carpenter's tool",
            "messy cloth",
            "silk cloth",
            "collapsed grave",
            "crumbled grave",
            "grave of ornamented with flowers",
            "brand new grave",
            "solemn tomb",
            "ancient tomb",
            "old grave",
            "altar",
            "ceremony altar",
            "fountain",
            "bunk bed",
            "rod of lightning bolt",
            "rod of slow",
            "quwapana",
            "aloe",
            "edible wild plant",
            "apple",
            "grape",
            "kiwi",
            "cherry",
            "guava",
            "carrot",
            "radish",
            "sweet potato",
            "lettuce",
            "dish",
            "imo",
            "api nut",
            "strawberry",
            "healthy leaf",
            "rainbow fruit",
            "qucche",
            "tangerine",
            "lemon",
            "green pea",
            "cbocchi",
            "melon",
            "leccho",
            "rod of magic mapping",
            "rod of cure",
            "corpse",
            "bottle of whisky",
            "<Ether Dagger>",
            "<Bow of Vinderre>",
            "worthless fake gold bar",
            "scroll of uncurse",
            "stone",
            "sickle",
            "staff",
            "spear",
            "ore piece",
            "lot of empty bottles",
            "basket",
            "empty bowl",
            "bowl",
            "tight rope",
            "dead fish",
            "straw",
            "animal bone",
            "pot",
            "katana",
            "scimitar",
            "battle axe",
            "hammer",
            "trident",
            "long staff",
            "short bow",
            "machine gun",
            "claymore",
            "ration",
            "bardiche",
            "halberd",
            "scroll of return",
            "figurine of warrior",
            "figurine of sword",
            "bejeweled chest",
            "chest",
            "safe",
            "scroll of magical map",
            "scroll of gain attribute",
            "scroll of wonder",
            "scroll of minor teleportation",
            "spellbook of magic mapping",
            "spellbook of oracle",
            "spellbook of return",
            "spellbook of cure minor wound",
            "spellbook of cure critical wound",
            "spellbook of cure <Eris>",
            "spellbook of cure <Jure>",
            "bottle of beer",
            "horn",
            "campfire",
            "portable cooking tool",
            "spellbook of magic arrow",
            "stick bread",
            "raw noodle",
            "sack of flour",
            "bomb fish",
            "poison",
            "spellbook of nether eye",
            "spellbook of chaos eye",
            "spellbook of nerve eye",
            "wakizashi",
            "spellbook of darkness beam",
            "spellbook of illusion beam",
            "spellbook of ice ball",
            "spellbook of fire ball",
            "spellbook of sound ball",
            "spellbook of chaos ball",
            "fire wood",
            "scarecrow",
            "broom",
            "long pillar",
            "broken pillar",
            "street lamp",
            "water tub",
            "comfortable table",
            "inner tube",
            "mysterious map",
            "suitcase",
            "wallet",
            "potion of restore body",
            "potion of restore spirit",
            "potion of potential",
            "scroll of curse",
            "spellbook of wishing",
            "rod of wishing",
            "well kept armor",
            "rack of good",
            "rack of accessories",
            "towel",
            "ragged table",
            "cabinet",
            "luxury bed",
            "vase",
            "high grade dresser",
            "neat bar table",
            "large bouquet",
            "chest of clothes",
            "giant bed",
            "plain bed",
            "coffin",
            "food processor",
            "soft bed",
            "cheap rack",
            "dresser",
            "clean bed",
            "bathtub",
            "pachisuro machine",
            "casino table",
            "slot machine",
            "darts board",
            "big foliage plant",
            "old shelf",
            "old bookshelf",
            "cheap bed",
            "cheap table",
            "neat rack",
            "simple dresser",
            "big cupboard",
            "sacred altar",
            "comfortable bed",
            "simple rack",
            "wide chair",
            "upright piano",
            "statue of cross",
            "stump",
            "dress",
            "table",
            "traveler's food",
            "throne",
            "golden pedestal",
            "golden statue",
            "skin",
            "blood",
            "eye",
            "heart",
            "bone",
            "fishing pole",
            "rune",
            "deed",
            "moonfish",
            "sardine",
            "flatfish",
            "manboo",
            "seabream",
            "salmon",
            "globefish",
            "tuna",
            "cutlassfish",
            "sandborer",
            "<Gloves of Vesda>",
            "<Blood Moon>",
            "<Ring of Steel Dragon>",
            "<Staff of Insanity>",
            "<Rankis>",
            "<Palmia Pride>",
            "shopkeeper's trunk",
            "scroll of greater identify",
            "scroll of vanish curse",
            "potion of defender",
            "spellbook of holy shield",
            "rod of silence",
            "spellbook of silence",
            "potion of silence",
            "spellbook of regeneration",
            "potion of troll blood",
            "spellbook of resistance",
            "potion of resistance",
            "spellbook of speed",
            "spellbook of slow",
            "potion of speed",
            "potion of slow",
            "rod of speed",
            "spellbook of hero",
            "potion of hero",
            "spellbook of weakness",
            "spellbook of elemental scar",
            "potion of weakness",
            "spellbook of holy veil",
            "scroll of holy veil",
            "rod of holy light",
            "spellbook of holy light",
            "spellbook of holy rain",
            "scroll of holy light",
            "scroll of holy rain",
            "scroll of mana",
            "rod of mana",
            "bottle of sulfuric",
            "gem cutter",
            "material box",
            "scroll of gain material",
            "spellbook of nightmare",
            "spellbook of knowledge",
            "scroll of knowledge",
            "rag doll",
            "barrel",
            "piano",
            "rope",
            "coffin",
            "manboo",
            "grave",
            "tuna fish",
            "whisky",
            "noble toy",
            "inner tube",
            "spellbook of detect objects",
            "scroll of detect objects",
            "rod of uncurse",
            "red treasure machine",
            "blue treasure machine",
            "treasure ball",
            "rare treasure ball",
            "vegetable seed",
            "fruit seed",
            "herb seed",
            "unknown seed",
            "artifact seed",
            "morgia",
            "mareilon",
            "spenseweed",
            "curaria",
            "alraunia",
            "stomafillia",
            "sleeping bag",
            "potion of weaken resistance",
            "scroll of growth",
            "scroll of faith",
            "potion of mutation",
            "potion of cure mutation",
            "spellbook of mutation",
            "banded mail",
            "plate mail",
            "ring mail",
            "composite mail",
            "chain mail",
            "pope robe",
            "light mail",
            "coat",
            "breast plate",
            "bulletproof jacket",
            "gloves",
            "plate gauntlets",
            "light gloves",
            "composite gauntlets",
            "small shield",
            "round shield",
            "shield",
            "large shield",
            "kite shield",
            "tower shield",
            "shoes",
            "boots",
            "tight boots",
            "armored boots",
            "composite girdle",
            "plate girdle",
            "armored cloak",
            "cloak",
            "feather hat",
            "heavy helm",
            "knight helm",
            "helm",
            "composite helm",
            "peridot",
            "talisman",
            "neck guard",
            "charm",
            "bejeweled amulet",
            "engagement amulet",
            "composite ring",
            "armored ring",
            "ring",
            "engagement ring",
            "stethoscope",
            "scroll of ally",
            "rod of domination",
            "spellbook of domination",
            "crossbow",
            "bolt",
            "spellbook of web",
            "rod of web",
            "machine",
            "computer",
            "training machine",
            "camera",
            "microwave oven",
            "server",
            "storage",
            "trash can",
            "chip",
            "blank disc",
            "shot gun",
            "pop corn",
            "fried potato",
            "cyber snack",
            "scroll of inferior material",
            "scroll of change material",
            "scroll of superior material",
            "figurine",
            "card",
            "little sister's diary",
            "scroll of enchant weapon",
            "scroll of greater enchant weapon",
            "scroll of enchant armor",
            "scroll of greater enchant armor",
            "heir trunk",
            "deed of heirship",
            "laser gun",
            "energy cell",
            "<Rail Gun>",
            "scroll of recharge",
            "bottle of water",
            "rod of change creature",
            "rod of alchemy",
            "bottle of dye",
            "wing",
            "deed of museum",
            "deed of shop",
            "tree of beech",
            "tree of cedar",
            "tree of fruitless",
            "tree of fruits",
            "dead tree",
            "tree of zelkova",
            "tree of palm",
            "tree of ash",
            "furnance",
            "fireplace",
            "stove",
            "giant foliage plant",
            "big table",
            "painting of madam",
            "painting of landscape",
            "painting of sunflower",
            "statue of cat",
            "black crystal",
            "snow man",
            "deed of farm",
            "deed of storage house",
            "disc",
            "rod of wall creation",
            "spellbook of wall creation",
            "salary chest",
            "spellbook of healing rain",
            "scroll of healing rain",
            "spellbook of healing hands",
            "rod of healing hands",
            "feather",
            "gem seed",
            "magical seed",
            "shelter",
            "seven league boots",
            "vindale cloak",
            "aurora ring",
            "potion of cure corruption",
            "master's delivery chest",
            "shop strongbox",
            "register",
            "textbook",
            "spellbook of acid ground",
            "rod of acid ground",
            "acidproof liquid",
            "fireproof blanket",
            "coldproof blanket",
            "spellbook of fire wall",
            "rod of fire wall",
            "jerky",
            "deed of ranch",
            "egg",
            "bottle of milk",
            "shit",
            "playback disc",
            "molotov",
            "kitty bank",
            "freezer",
            "modern rack",
            "rod of make door",
            "spellbook of make door",
            "torch",
            "candle",
            "fancy lamp",
            "modern lamp",
            "handful of snow",
            "tree of naked",
            "tree of fir",
            "snow scarecrow",
            "mini snow man",
            "snow barrel",
            "modern lamp",
            "statue of holy cross",
            "pillar",
            "stained glass window",
            "christmas tree",
            "snow man",
            "christmas tree",
            "giant's shackle",
            "empty bottle",
            "holy well",
            "president's chair",
            "green plant",
            "money tree",
            "barbecue set",
            "giant cactus",
            "square window",
            "window",
            "triangle plant",
            "house board",
            "nice window",
            "king's bed",
            "flower arch",
            "bill",
            "tax master's tax box",
            "bait",
            "fish",
            "fished junk",
            "love potion",
            "treasure map",
            "small medal",
            "cat sister's diary",
            "girl's diary",
            "shrine gate",
            "bottle of hermes blood",
            "<Sage's Helm>",
            "spellbook of incognito",
            "disguise set",
            "material kit",
            "moon gate",
            "flying scroll",
            "panty",
            "leash",
            "mine",
            "lockpick",
            "skeleton key",
            "scroll of escape",
            "happy apple",
            "unicorn horn",
            "cooler box",
            "rice barrel",
            "eastern bed",
            "decorated window",
            "king drawer",
            "menu board",
            "black board",
            "sofa",
            "flowerbed",
            "toilet",
            "craft cupboard",
            "sink",
            "junk",
            "double bed",
            "hero cheese",
            "eastern lamp",
            "eastern window",
            "chochin",
            "partition",
            "spellbook of darkness arrow",
            "<Dal-i-thalion>",
            "magic fruit",
            "monster heart",
            "speed ring",
            "statue of Opatos",
            "statue of Lulwy",
            "sister's love fueled lunch",
            "book",
            "art",
            "canvas",
            "nuclear bomb",
            "secret treasure",
            "<Wind Bow>",
            "<Winchester Premium>",
            "<Kumiromi Scythe>",
            "<Elemental Staff>",
            "<Holy Lance>",
            "<Lucky Dagger>",
            "<Gaia Hammer>",
            "Lulwy's gem stone of god speed",
            "Jure's gem stone of holy rain",
            "Kumiromi's gem stone of rejuvenation",
            "gem stone of Mani",
            "gene machine",
            "monster ball",
            "statue of Jure",
            "ancient book",
            "iron maiden",
            "guillotine",
            "pan flute",
            "lute",
            "harmonica",
            "harp",
            "eastern partition",
            "<Axe of Destruction>",
            "spellbook of magic ball",
            "spellbook of magic laser",
            "potion of salt solution",
            "little ball",
            "town book",
            "deck",
            "rabbit's tail",
            "whistle",
            "vomit",
            "<Beggar's Pendant>",
            "potion of descent",
            "<Stradivarius>",
            "book of resurrection",
            "scroll of contingency",
            "spellbook of contingency",
            "potion of evolution",
            "deed of dungeon",
            "shuriken",
            "grenade",
            "secret experience of Kumiromi",
            "<Vanilla Rock>",
            "secret experience of Lomias",
            "<Shena's Panty>",
            "<Claymore>",
            "happy bed",
            "statue of Ehekatl",
            "<Arbalest>",
            "<Twin Edge>",
            "music ticket",
            "<Kill Kill Piano>",
            "<Al'ud>",
            "<Shield of Thorn>",
            "<Crimson Plate>",
            "gift",
            "token of friendship",
            "spellbook of 4 dimensional pocket",
            "spellbook of harvest",
            "sand bag",
            "small gamble chest",
            "scythe",
            "fireproof liquid",
            "scroll of name",
            "fortune cookie",
            "<Frisia's Tail>",
            "<Unknown Shell>",
            "<Hiryu-To>",
            "license of the void explorer",
            "plank of Carneades",
            "Schrodinger's cat ",
            "heart",
            "tamer's whip",
            "book of Bokonon",
            "summoning crystal",
            "statue of Creator",
            "upstairs",
            "downstairs",
            "new year's gift",
            "kotatsu",
            "daruma",
            "kagami mochi",
            "mochi",
            "<Five Horned Helm>",
            "<Mauser C96 Custom>",
            "lightsabre",
            "Garok's hammer",
            "<Gould's Piano>",
            "festival wreath",
            "pedestal",
            "counter",
            "red stall",
            "blue stall",
            "Jure's body pillow",
            "new year's decoration",
            "miniature tree",
            "bottle of soda",
            "blue capsule drug",
            "tomato",
            "large bookshelf",
            "luxury cabinet",
            "special steamed meat bun",
            "statue of Kumiromi",
            "statue of Mani",
            "luxury sofa",
            "deer head",
            "fur carpet",
            "kitchen knife",
            "dish",
            "recipe",
            "recipe holder",
            "bottle of salt",
            "sack of sugar",
            "puff puff bread",
            "skull bow",
            "pot for testing",
            "frying pan for testing",
            "<Dragon Slayer>",
            "putitoro",
        };
    }
}
